quarkus:
  http:
    port: 8082
    cors:
      ~: true
      origins: http://localhost:5173
      methods: GET
  rest-client:
    vehicle-api:
      url: http://localhost:8080
    driver-api:
      url: http://localhost:8080

